### ISSUE TITLE
Multiple Solutions with multiple services and one docker-compose project

### ISSUE THREAD

**Issue by prochnowc** [Microsoft/DockerTools#112]
We have very big project consisting of ~10 micro services. Each micro service lives in it's own solution.
The project structure is like this:

Root
|- Common
|--| Common.Lib1
|--| Common.Lib2
|- Service1/
|--| Service1.sln
|--| Service1.Lib/
|--| Service1.App/
|- Service2/
|--| Service2.sln
|--| Service2.Lib/
|--| Service2.App/

How is it possible to add docker support to the whole project?

I tried to add docker-compose project to the root and adding all services to the docker-compose.yml file.  Also i added the docker-compose project to each of the Service*.sln's.

But when opening Service1.sln it can only build the container for Service1. When trying to build the container for Service2 (which is present in docker-compose.yml) the build bails out with src files not being found.

**Comment by kazha** [comment]
Not sure why you would want to build all other services from Service1 as it has to live it's own life. However I would suggest to build compose from root dir. check if your config is correct and path to Dockerfiles for each project are valid.
should be something like this
container_name: Service1
    build:
      image: Service1
      context: ./Service1
      dockerfile: Dockerfile
where context path containes dockerfile
if config is ok "docker-compose build" from root dir should work as intended

**Comment by prochnowc** [comment]
@kazha The problem is that all containers are built automatically when i run the docker-compose project.
I already tried to put docker-compose in root dir. But as already said - it bails out because the build seems to copy sources before container build to some place. When building Service1 which in turns builds container for Service2 the sources cant be found (probably because Service2 is not in the solution).

**Comment by kazha** [comment]
Check your docker-compose.yml (the one in the root dir) and verify the paths defined for "dockerfile" and "context". Works for me at least Linux container with default Dockerfile

```
FROM microsoft/dotnet:2.1-sdk
ARG source
WORKDIR /app
EXPOSE 80
COPY ${source:-obj/Docker/publish} .
ENTRYPOINT ["dotnet", "Service1.dll"]

```
If all seems ok, i'd suggest to post actual error.

**Comment by sanderdegroot** [comment]
Check the contents of your obj/Docker/publish/ directory (relative to the Service2 project directory). If it's empty, that's why it's failing. Running a **Release** build of your project should cause your compiled binaries to get put there.

The reason for this is because of the `COPY ${source:-obj/Docker/publish} .` line in the default Dockerfile seen in @kazha 's comment above mine. `${source:-obj/Docker/publish}` is Docker variable substitution syntax which means: if the `source` variable doesn't have a value or is an empty string, return `obj/Docker/publish`, else return the value of `source`.

Normally Visual Studio assigns a value to `source` depending on whether you're debugging in Debug or Release mode, but if you're running `docker compose up` manually, that variable won't be populated, and it'll default to trying to copy the compiled binaries from `obj\Docker\publish`, relative to the project directory, into your container. A build in Release mode should put your binaries in that folder (in addition to the `bin\Release` folder).

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please let us know, we are happy to take a look!
