### ISSUE TITLE
The DOCKER_REGISTRY variable is not set. Defaulting to a blank string.

### ISSUE THREAD

**Issue by MarxiRo** [microsoft/DockerTools#130]
Hi 

I'm new for docker 

I am having trouble with launching .NET Core 2.1 project on Docker container. When I try to run docker 
it fails.

The error log is :  

Severity	Code	Description	Project	File	Line	Suppression State
Error  The DOCKER_REGISTRY variable is not set. Defaulting to a blank string.
Building webapplication3
Service 'webapplication3' failed to build: Get https://registry-1.docker.io/v2/microsoft/dotnet/manifests/2.1-aspnetcore-runtime-nanoserver-1709: unauthorized: incorrect username or password.

For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	363

**Comment by martinmani** [comment]
Any solution for this?

**Comment by haniamr** [comment]
Hi @MarxiRo, what happens if you run this command directly:
`docker pull microsoft/dotnet:2.1-aspnetcore-runtime-nanoserver-1709`

If you still get the unauthorized error, then I'd suggest running `docker login` and try again (although pulling this image shouldn't require authentication).

**Comment by jaishmathews** [comment]
I had this issue and has resolved after taken below steps.
1. Run Visual Studio as Administrator
2. Your running Docker host should logged-in to your DockerHub account. This is very important

The main reason for this issue is Visual Studio couldn't download nano server image from docker. So always make sure that you logged in to your dockerhub account from running host. You can verify this through Visual Studio output window, which I copied below. How this helps.

1>The DOCKER_REGISTRY variable is not set. Defaulting to a blank string. - **_Here Issue_**
1>Building webapplication2 - **_Below success_**
1>Step 1/3 : FROM microsoft/aspnetcore:2.0-nanoserver-sac2016 AS base
1>2.0-nanoserver-sac2016: Pulling from microsoft/aspnetcore
1>Digest: sha256:1badca91837973c27881d68195c880921cf269523c9723c122e96d239ab11a0f
1>Status: Downloaded newer image for microsoft/aspnetcore:2.0-nanoserver-sac2016
1> ---> 701fc8160212
1>Step 2/3 : WORKDIR /app
1>Removing intermediate container 638818fa9593
1> ---> a4eed3de79d6
1>Step 3/3 : EXPOSE 80
1> ---> Running in d836748bd65c
1>Removing intermediate container d836748bd65c
1> ---> 445ae58fb2ae
1>Successfully built 445ae58fb2ae
1>Successfully tagged webapplication2:dev
1>Creating dockercompose5288439535790493436_webapplication2_1 ...
1>Creating dockercompose5288439535790493436_webapplication2_1 ... done

**Comment by gruberchris** [comment]
I am using Visual Studio 2017 v15.7.6 and Docker for Windows CE 18.06.0 (19098) on Windows 10.

every night i come home from the office, boot up my PC and open my latest project in Visual Studio. And every night I try to debug my ASP.NET CORE 2.1 project with my docker-compose project as the startup project and every night it fails with this error message reported here:

*The DOCKER_REGISTRY variable is not set. Defaulting to a blank string.*

And then, every night, I go to my docker for windows icon running in my system tray and select to reset docker. I then repeat my attempt to debug and it works!! It works until I shut my PC down when its time to go to sleep and then the next day comes and I repeat this. Its been 5 days in a roll so far :-)

For me, it doesn't matter if I run VS 2017 as an Administrator or not and it doesn't seem to matter if my docker for windows is logged in with my docker account or not (I am and I have been, fyi).

It looks to me like this issue is considered Closed. I really think you should reopen this issue. I'm happy to provide you with whatever information you need to troubleshoot this issue.

Otherwise, keep up the good work that everyone on this project is doing!

**Comment by gnagagit** [comment]
Created simple asp.net core angular 6 app in Visual Studio 2017 15.7.5. With docker(Linux) enabled https disabled, using Windows 10 OS.
SolutionName/ProjectName: Angularaspnetcore , Use developer command prompt 
npm install -g @angular/cli
cd..
ng new Angularaspnetcore
cd Angularaspnetcore
Build Angularaspnetcore solution from Visual studio with DEBUG mode, builds without any issues. I see the dev image created in docker.
change to RELEASE mode and build the Angularaspnetcore solution in Visual studio 2017, builds without any issues. I see the latest image created in docker. Able to containerize the image and run.
ng build         -- This executes without any issues
re-build Angularaspnetcore solution from Visual studio with RELEASE mode, builds without any issues. I see the dev image created in docker
ng build –prod           -- This executes without any issues
re-build Angularaspnetcore solution from Visual studio with RELEASE mode, getting below error

Severity	Code	Description	Project	File	Line	Suppression State
Error		The DOCKER_REGISTRY variable is not set. Defaulting to a blank string.
Building [58736] Failed to execute script docker-compose
[58736] Failed to execute script docker-compose
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 127, in perform_command
  File "compose\cli\main.py", line 282, in build
  File "compose\project.py", line 378, in build
  File "compose\service.py", line 1067, in build
  File "site-packages\docker\api\build.py", line 154, in build
  File "site-packages\docker\utils\build.py", line 31, in tar
  File "site-packages\docker\utils\build.py", line 79, in create_archive
  File "tarfile.py", line 1803, in gettarinfo
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\ Angularaspnetcore\\ Angularaspnetcore \node_modules\\.cache\\uglifyjs-webpack-plugin\\content-v2\\sha512\\59\\1f\\819ba6767725b14814cba16a59ef3bcca88f03c635104c87a60fd1453353858d1fae4b2a84c8b022caa2055754530846869be3a7e59b0a8fbd501ade1b75'.

For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.Docker.targets	111

**Comment by lee-alderdice** [comment]
Firstly, I am completely new to Docker and Container orchestration so apologies if this is a bit 101 but I am getting this same error having created a vanilla .NetCore 2.0 MVC Web App with Individual Account authentication and nothing further.  

`docker run microsoft/dotnet` as per @haniamr above doesn't error but that is about it.

Is there are workaround?  I had been trying to setup this up through bitbucket pipelines but having failed thought i would prototype it locally but got stuck at this issue.

**Comment by MulderLiu** [comment]
I am using Visual Studio 2017 v15.8.1 and Docker for Windows CE 18.06.0 (19098) on Windows 10.

Under Release condition, I will encounter this error **"The DOCKER_REGISTRY variable is not set. Defaulting to a blank string."**
but Debug is OK!!!!

**Comment by HaoTsien** [comment]
I'm using VS 2017 for mac and Docker and I can see same error "The DOCKER_REGISTRY variable is not set. Defaulting to a blank string".

**Comment by haniamr** [comment]
@gruberchris I'd be happy to help if you can provide me with the build output logs at the time of failure.

**Comment by s-leonard** [comment]
I've had this error many times and the thing that fixes it for me, is to right click on the solution and add a new asp.net core api with docker support. 

Then clicking Debug works. After that I remove the project from the solution and remove the folder in file explorer. 

Finally I remove the service from the docker-compose.yml file AND the docker-compose.override.yaml below it. 

I know this seem to be a weird work around, but whatever it does behind the scenes, fixes the issue.

**Comment by babenkov-aa** [comment]
> Created simple asp.net core angular 6 app in Visual Studio 2017 15.7.5. With docker(Linux) enabled https disabled, using Windows 10 OS.
> SolutionName/ProjectName: Angularaspnetcore , Use developer command prompt
> npm install -g @angular/cli
> cd..
> ng new Angularaspnetcore
> cd Angularaspnetcore
> Build Angularaspnetcore solution from Visual studio with DEBUG mode, builds without any issues. I see the dev image created in docker.
> change to RELEASE mode and build the Angularaspnetcore solution in Visual studio 2017, builds without any issues. I see the latest image created in docker. Able to containerize the image and run.
> ng build -- This executes without any issues
> re-build Angularaspnetcore solution from Visual studio with RELEASE mode, builds without any issues. I see the dev image created in docker
> ng build –prod -- This executes without any issues
> re-build Angularaspnetcore solution from Visual studio with RELEASE mode, getting below error
> 
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	The DOCKER_REGISTRY variable is not set. Defaulting to a blank string.
> Building [58736] Failed to execute script docker-compose
> [58736] Failed to execute script docker-compose
> Traceback (most recent call last):
> File "docker-compose", line 6, in 
> File "compose\cli\main.py", line 71, in main
> File "compose\cli\main.py", line 127, in perform_command
> File "compose\cli\main.py", line 282, in build
> File "compose\project.py", line 378, in build
> File "compose\service.py", line 1067, in build
> File "site-packages\docker\api\build.py", line 154, in build
> File "site-packages\docker\utils\build.py", line 31, in tar
> File "site-packages\docker\utils\build.py", line 79, in create_archive
> File "tarfile.py", line 1803, in gettarinfo
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\ Angularaspnetcore\ Angularaspnetcore \node_modules\.cache\uglifyjs-webpack-plugin\content-v2\sha512\59\1f\819ba6767725b14814cba16a59ef3bcca88f03c635104c87a60fd1453353858d1fae4b2a84c8b022caa2055754530846869be3a7e59b0a8fbd501ade1b75'.
> 
> For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.Docker.targets	111

File path exceeds 255 characters

**Comment by AndriyChernetskyy** [comment]
> I am using Visual Studio 2017 v15.7.6 and Docker for Windows CE 18.06.0 (19098) on Windows 10.
> 
> every night i come home from the office, boot up my PC and open my latest project in Visual Studio. And every night I try to debug my ASP.NET CORE 2.1 project with my docker-compose project as the startup project and every night it fails with this error message reported here:
> 
> _The DOCKER_REGISTRY variable is not set. Defaulting to a blank string._
> 
> And then, every night, I go to my docker for windows icon running in my system tray and select to restart docker. I then repeat my attempt to debug and it works!! It works until I shut my PC down when its time to go to sleep and then the next day comes and I repeat this. Its been 5 days in a roll so far :-)
> 
> For me, it doesn't matter if I run VS 2017 as an Administrator or not and it doesn't seem to matter if my docker for windows is logged in with my docker account or not (I am and I have been, fyi).
> 
> I'm happy to provide you with whatever information you need to troubleshoot this issue.
> 
> Otherwise, keep up the good work that everyone on this project is doing!

This really works! Strange solution but it works. I think the reason is because port could be used by some other tool. Thanks for solution!

**Comment by H286424** [comment]
I am not able to build my .net core 2.1 app, getting same issue "The DOCKER_REGISTRY variable is not set. Defaulting to a blank string."
Do we need to set the docker_Registry variable in system environment variables?

**Comment by sameer-awate** [comment]
In Docker Settings -> Network, I switched the DNS Server setting to "Fixed" (left it default to 8.8.8.8) and it worked for me. 

![image](https://user-images.githubusercontent.com/28428838/53336349-0eb72400-3924-11e9-975c-42ecf22e6b10.png)

**Comment by renatogbp** [comment]
This happened to me, and I noticed when I removed an image from my docker-compose file I've forgot to remove it from other containers' "depends_on"
