### ISSUE TITLE
VS debugger won't start when Dockerfile in a subdirectory. 

### ISSUE THREAD

**Issue by nur858** [Microsoft/DockerTools#148]
I have `Dockerfile` in `WebApplication1/docker/`.  VS builds container fine but it doesn't attach debugger when dockerfile is in subdirectory.  As soon as I move dockerfile to project root (WebApplication1/Dockerfile) , everything works as expected including debugging.    

docker-compose.yml:
-----------------------
```services:
  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/docker/Dockerfile
```
VS version : 15.7.5
Docker version: 18.06.1-ce-win73

**Comment by bwateratmsft** [comment]
Hey @nur858, this behavior is by-design. It is possible and desirable to have a docker-compose project that can start containers without attaching--for instance, a MySQL container for storage--so, Visual Studio only attaches to a container if it can associate a service (in the docker-compose) to a project in the solution. The only way to do this is if the Dockerfile is in the same folder as the csproj. You will need to move your dockerfile to be adjacent to the csproj to automatically attach. Otherwise, you can manually attach after launch.

**Comment by nur858** [comment]
Thanks @bwateratmsft for quick response.  Any chance this can be made configurable? It possible to add linting rules, specification testing to docker and to keep them in a folder along with dockerfile is desirable from code organization point of view.

**Comment by bwateratmsft** [comment]
@nur858 I will file a work item to suggest changing this.
