### ISSUE TITLE
OSError: Can not read file in context: *.dbmdl

### ISSUE THREAD

**Issue by Varorbc** [microsoft/DockerTools#149]
There is a database project in our solution, and the following error message will appear when building the docker:
OSError: Can not read file in context: *.dbmdl

**Comment by haniamr** [comment]
@Varorbc thanks for reporting, so it's a database project with docker enabled? Or is it a web project with a *.dbml file in it? I've tried the latter and it works fine.

**Comment by Varorbc** [comment]
@haniamr thank you.A total of 2 projects, one database project, one web project, the database project is not quoted by the web project

**Comment by haniamr** [comment]
So you manually added a dockerfile to the database project and referenced that in the yaml files, correct? I'm not sure why you'd want to containerize a database project with dbml file(s) that is not referenced by a web project? 

In general, we do not support "Database projects" and that's why you won't see the option enabled through the UI but if you give me more info on the use case I'll be happy to log that as an enhancement.

**Comment by Varorbc** [comment]
No, we have a lot of projects in our solution that happen to have a database project, and that's the kind of error that happens when we build a container image for a web project.

**Comment by haniamr** [comment]
Can you share a sample code for that scenario so that I can better understand the issue?

**Comment by goldengrisha** [comment]
I suppose his context in docker-compose or in docker file points to the root of the app, while vs' process holds this file that's why it can't be copied by docker daemon.
My local workaround is reload db project.

**Comment by Varorbc** [comment]
@goldengrisha @haniamr I guess that's why you're talking, but my docker file was created through vs, so it needs to be solved fundamentally.

**Comment by sgreenmsft** [comment]
To address this we will add these two settings to the dockerignore file that VS generates:
**/*.dbmdl
**/*.jfm

**Comment by qwergram** [comment]
Perhaps a dead thread, but for future googler/bingers, I've reached a similar issue. However instead of trying to process a `.dbmdl` file, it was reading my `.docx` files from a directory above as well. The issue was in the `.devcontainer/devcontainer.json`.

In the option: `dockerComposeFile`, if the first element of that array is a step up, e.g.:

```json
"dockerComposeFile": [
	"..\\docker-compose.yml",
	"..\\docker-compose.override.yml",
	"docker-compose.yml"
],
```

Then it will run all subsequent docker-compose.yml and Dockerfiles as if it were in that upper directory. In the VSCode generated `docker-compose.yml`, it attempted another relative filepath in the build:

```
build:
  context: ..
```

Which made it read my entire G:\ drive. Not sure if this is a bug, or if I'm just so new to Docker this was inherently obvious.
