### ISSUE TITLE
Docker Compose option for Console Applications as well as Web Apps

### ISSUE THREAD

**Issue by rmccabe24** [Microsoft/DockerTools#158]
Not sure how to raise a feature request, so will try here.

When I scoffold up a new .net Core Web project in Visual Studio, I get a checkbox for "Enable Docker Support".  I'd like to see this for a .net Core Console application also and that, when checked, I get a dcproj included in my solution for the console application.  This would be handy!  Currently I have to copy my dcproj out of a web app, across into my console app.

:-)

**Comment by bwateratmsft** [comment]
We have some of this planned for Visual Studio 2019. There won't be an "Enable Docker support" checkbox, since there's not a second form after the Create Project page (it goes directly from selecting the project type, .NET Core Console, to the opened project, since there's no template selection), but you will be able to right click the project after creation and do Add > Docker Support and/or Add > Container Orchestrator Support.

**Comment by rmccabe24** [comment]
Excellent!  Looking forward to having it included :)
