### ISSUE TITLE
Debugging Docker Containers not working with VS for Mac

### ISSUE THREAD

**Issue by quiettimbo** [microsoft/DockerTools#173]
I ran through the example here: https://github.com/Microsoft/vs4mac-labs/tree/master/Docker/Getting-Started and things seem to work fine (once I had added the NuGetFallbackFolder fileshare) except for the breakpoints.
If I set a breakpoint it seems to hit - the request does not complete but Visual Studio is unaffected.  There is no notification that the breakpoint has hit or any obvious way to continue.

I am using:
    Visual Studio for Mac Enterprise v 7.8.3 build 2.
    Docker Desktop Community v2.0.0.3 (31259)

**Comment by sgreenmsft** [comment]
Thanks for bringing this to our attention.  We've found the source of the problem and a fix for this issue should be released later today.  VS for Mac will automatically download the fix for the broken component (vsdbg) after a day or so, but if you'd like to get it faster then you can delete the .vsdbg folder from your user profile (~/.vsdbg).

**Comment by bwateratmsft** [comment]
@sgreenmsft looks like this is the same as https://developercommunity.visualstudio.com/content/problem/499991/unable-to-debug.html?

**Comment by haniamr** [comment]
This issue is fixed in the link that Brandon shared above, please shout out if you're still seeing any problems.
