### ISSUE TITLE
How to run not debug version of Linux docker image under windows

### ISSUE THREAD

**Issue by OlegPNN** [microsoft/DockerTools#203]
Hi in DockerTools community.
I'm pretty sure this is not a bag, but I'm bit lost on this step.
Under windows and VS2019 i've made ASP .NET Core project which docker linux support which is sucessfully can be debugged under docker configuration. Solution is under https://github.com/OlegPNN/ASP.NET-core-docker-.git. 
Docker file uses mcr.microsoft.com/dotnet/core/aspnet:2.1-stretch-slim image.
..
FROM mcr.microsoft.com/dotnet/core/aspnet:2.1-stretch-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:2.1-stretch AS build
WORKDIR /src
...

Now i'm trying on the same machine to run linux image without debug mode.
I've run command like 
docker build -f "C:\Olegus\Projects\HelloWorld\HelloWorld\HelloWorldAPI\Dockerfile" -t helloworldapi "C:\Olegus\Projects\HelloWorld\HelloWorld" pointed to docker file generated by VS in order to build "prod" version and it compled sucessfully.

When I run in concole command like 
docker run -it -p 80:80 -p 443:443 -e ASPNETCORE_URLS="https://+443;http://+80" -e ASPNETCORE_HTTPS_PORT=443 -v "C:\App" -v "${APPDATA}/ASP.NET/Https"  -e "ASPNETCORE_ENVIRONMENT=Development" -e "ASPNETCORE_HTTPS_PORT=443" --restart=on-failure -d helloworldapi

it return hash and trying to run, but docker ps shows it permanently crashes and trying to restart. Without restart option it crashing once and I can't find image within running containers.

I think the reason, I'm setting wrong work directories given from some examples. But in any case directory path for debug is not applicable for this case. Like
-v "C:\Users\Profile\vsdbg\vs2017u5:/remote_debugger:rw" -v "C:\Olegus\Projects\HelloWorld\HelloWorld\HelloWorldAPI:/app" -v "C:\Users\Profile\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro" -v "C:\Users\Profile\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro" -v "C:\Users\Profile\.nuget\packages\:/root/.nuget/fallbackpackages2" -v "C:\Program Files\dotnet\sdk\NuGetFallbackFolder:/root/.nuget/fallbackpackages"

Question is: which path shall I use runnig linux image with mcr.microsoft.com/dotnet/core/aspnet:2.1-stretch-slim  in docker run command?

**Comment by bwateratmsft** [comment]
Hey @OlegPNN , another user faced some similar issues here: https://github.com/microsoft/DockerTools/issues/198

In order to run it in a production-like way, an SSL certificate is needed; the location it's at needs to be mapped in. The user there mapped it in to /https, at /https/aspnetapp.pfx. He used environment variables to control the path that ASP.NET Core looks for the cert (ASPNETCORE_Kestrel__Certificates__Default__Path), and the password (ASPNETCORE_Kestrel__Certificates__Default__Password).

For example, assuming you've created a PFX file with password ABC123, your "docker run" command might look like this:
`docker run -it -p 80:80 -p 443:443 -e ASPNETCORE_URLS=https://+:443;http://+:80 -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx -e ASPNETCORE_Kestrel__Certificates__Default__Password=ABC123 -v "C:\path\to\sslCertFolder:/https:ro"`

The ASPNETCORE_ENVIRONMENT variable should be left unchanged for a production or production-like run, and ASPNETCORE_HTTPS_PORT uses 443 by default so it doesn't need to be explicitly set here.

Note that opening 80 and 443 (on the host) may require running on an elevated command prompt, and probably won't work if IIS or IIS Express are running.

**Comment by OlegPNN** [comment]
Thanks Brandon for explanation and similar issue link. I didn't pay attention that certificate configuration is a must and appropriate partition with certificate should be maped. Yes, docker container is not started in case 80 or 443 ports are hold by another app.
