### ISSUE TITLE
Debuggin large number of projects slow: Allow debug of a single service out of a set of microservices

### ISSUE THREAD

**Issue by iAlexanderMoon** [Microsoft/DockerTools#23]
I have an soa architecture with many dotnet core webapi services in my compose file.
Most times I am working on only one of many (but need the many running).

When I debug the docker-compose project it compiles ALL of them... recreates all of them.
I would like the tool to be able to debug a single service 
```
docker-compose .. up -d <servicename>
```

**Comment by alexvy86** [comment]
I see it's been a while since the issue was raised, but in case this helps anyone: VS Docker Tools apparently only compiles services that have a `build` section defined in the docker-compose file. so what I've been doing to debug a single service out of a bunch is to remove the `build` section of all the other ones (from `docker-compose.yml` and/or `docker-compose.override.yml`). As long as the other services have an `image` section defined and the corresponding image is available (locally or in a docker repo you can pull from), the `docker-compose` project can be built, it won't compile those other services, and the one with the `build` section will be started such that you can debug it.

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!
