### ISSUE TITLE
Startup project not easily changeable. Options are not fully displayed for ease of use.

### ISSUE THREAD

**Issue by paddywaan** [microsoft/DockerTools#275]
It appears as though whenever "docker-compose" is selected, but the user desires to build without docker debug integration, selecting the main project as the startup project results in the docker-compose project being removed from the startup list. Similarly the opposite happens, but in my experience this only occurs on a fresh project. On my existing project, the code projects are never removed from the startup selection, only the docker compose option once anything else is selected, please see video attached:

https://streamable.com/bb4im7
[Startup-Project.s.mp4.zip](https://github.com/microsoft/DockerTools/files/5413500/Startup-Project.s.mp4.zip)

**Comment by pratiksanglikar** [comment]
Hi @paddywaan ,
I watched the video and still confused as to where the problem is.
1. If `docker-compose` is set as a startup project, then you can only debug through the `docker-compose` configuration.
2. If a particular project is set as a startup project, then you can debug with either `Docker` or other default configurations like IISExpress or Kestrel.
3. Setting multiple startup projects of which one includes `docker-compose` is a tricky one where it will launch all the services in the docker-compose project, and then any other projects that you have selected as a startup project. If any project among multiple startup projects happens to be a service in the docker-compose, then it is not a valid scenario.

With that being said, I would like to know what is the use case that you are trying to work and I can then work through the workaround for it.

**Comment by elangelo** [comment]
As some feedback... I think that normally any project added to your solution is available to select from the dropdown in the debug toolbar.  This is not the case for docker-compose projects. 
Just to elaborate:
If you have 4 .csproj projects in your solution, you can select any of those from the debug toolbar dropdown. You also have the option to right click on any of the projects and choose that one as a startup project. That would just switch the dropdown in the toolbar.
With a docker-compose project in your solution this all changes all of a sudden. You have to right click on the project to make it runnable and if it's runable you can no longer use the toolbar to select an other project. 
It's just very inconsistent and it's very unintuitive for ppl used to work with the drop down in the debug toolbar.
