### ISSUE TITLE
Default scaffolded Visual Studio Dockerfile doesn't run in shell or Azure Pipelines

### ISSUE THREAD

**Issue by tymur999** [microsoft/DockerTools#292]
The default scaffolded Visual Studio Dockerfile does not support being used in shell such as with _Docker build_ or _Docker run_, including pipelines such as Github Actions. 

Specifically, I'm getting an issue where "Skipping <project name> project because it was not found", when the image is building. This happens with all referenced projects, which results in the build not being able to complete. Is there any makeshift fix right now for this issue?

**Comment by NCarlsonMSFT** [comment]
To support project to project references the Dockerfiles from the VS tools are always scaffolded using the solution folder. Because of this when building from the commandline you will need to specify the build context and the path to the dockerfile. For example:
```docker build -f Dockerfile ..```
For more details see: https://docs.microsoft.com/en-us/visualstudio/containers/container-build?view=vs-2019#docker-build

**Comment by tymur999** [comment]
Oh okay, I see. Thanks
