### ISSUE TITLE
Project volume does not include linked files

### ISSUE THREAD

**Issue by andrew-hampton** [microsoft/DockerTools#378]
When debugging within Visual Studio using Docker it creates a volume with a bind point for c:\app for the project directory. However, this misses any project files that aren't in the project directory, but are linked.

Example:
```
  <ItemGroup>
    <Content Include="..\Startup.ps1">
      <Link>Startup.ps1</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```

Appreciate any suggestions on how to handle this scenarios

**Comment by NCarlsonMSFT** [comment]
@andrew-hampton You shouldn't need to reference it from the source folder and should instead be able to access it from your output directory.
If you're using a command line app the output directory will be your working directory. Otherwise, you can Use [`Assembly.GetExecutingAssembly()`](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getexecutingassembly)[`.Location`](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assembly.location) to get the path for your assembly and the script should be in the same folder (unless you've customized your build).
