### ISSUE TITLE
Unable to Connect to Local SQL Server from Docker Container

### ISSUE THREAD

**Issue by RehanSaeed** [Microsoft/DockerTools#40]
I have a local SQL Server instance running on my Windows dev machine. I want to connect to it from my Linux docker container using Entity Framework Core. My connection string of `Data Source=localhost` fails, I've also tried several IP addresses and port combinations but can't seem to connect to my SQL Server.

I asked this question on StackOverflow [here](https://stackoverflow.com/questions/45836546/) and someone mentioned that I could use the `--net=host` option to share the host network with the container. I tried adding `network_mode: host` to my `docker-compose.yml` or `docker-compose.override.yml` file but I get an error in both cases:

![untitled](https://user-images.githubusercontent.com/2270364/29626156-ca60cf78-8825-11e7-9fab-2bb0fe019b17.png)

Is this a supported scenario? Am I supposed to be able to connect to my SQL Server using `localhost`? If not, am I supposed to use an IP address, if so what would that IP address be?

**Comment by guilhermecreste** [comment]
Hello, I resolved the communication from Docker container to a local service by changing the network mode to "bridge". For example, inside docker-compose.yml file edited it to reference the new network model: 

version: '3'

services:
  thenameoftheservice:
    image: thenameoftheimage
    **network_mode: bridge**
    build:
      context: .
      dockerfile: folderwheredockerfileis/Dockerfile

**Comment by RehanSaeed** [comment]
That didn't seem to work for me. I've added Docker support, used localhost in my connection string with a user Id and password instead of integrated security but I still get a timout.

**Comment by RehanSaeed** [comment]
I'm using VS 15.5.2 and it's multi-stage builds where the yml has changed a bit.

**Comment by guilhermecreste** [comment]
I see... Well, try to use the localhost IP Address 127.0.0.1, instead of localhost. Also, you can verify what is the network mode that your Docker container is using. Give a try with this command: docker inspect yourcontainername

You should see something like below in the output:
 "Networks": {
                "bridge": {

To verify what network you have for Docker, run this command: docker network list

Also, you can enter inside the docker container and try to ping your host... To enter in your docker container, run this command: docker exec -it yourcontainername /bin/bash. To quit the container, just type exit.

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!
