### ISSUE TITLE
Keep Container Running

### ISSUE THREAD

**Issue by DanPatten** [microsoft/DockerTools#436]
How do I keep a container running upon stopping from debugging in Visual Studio, I know I can detach the process but I want to keep the container running when I stop.

**Comment by NCarlsonMSFT** [comment]
Do you just want the container to keep running or the app in the container? Are you using a Dockerfile or the SDK based launch profile?

Assuming you want the full app running while not debugging, the easiest thing to do is start without debugging (Ctrl+F5):
![image](https://github.com/user-attachments/assets/8f5fd6fc-5deb-4e12-926c-790c223454e6)

**Comment by DanPatten** [comment]
I'm using a dockerfile, I want the container to always be running until I connect to it and debug and make changes in visual studio. When I stop the debugger I don't want th container to stop. I don't want to attach the debugger because I want fast mode and 1-click debugging.

**Comment by NCarlsonMSFT** [comment]
If you're using the Dockerfile based launch profile and the Debug configuration, what you're describing is the default behavior in VS. When you open the project warm-up (if enabled) will pull your base image and start a container with the local folders volume mounted ready for debugging. Then each debugging session reuses the same container (unless the Dockerfile has changed) running your locally built output in the existing container. Here are some docs on how debugging in a container in VS works: https://learn.microsoft.com/en-us/visualstudio/containers/container-build?view=vs-2022#debugging . Is this not working for you?

**Comment by DanPatten** [comment]
@NCarlsonMSFT Yes the debugger automatically attaches to a running instance if its already running but when I stop debugging using the Stop button in VS the dotnet process in the container stops and I have to manually run docker-compose up to start it again.

My entrypoint in Dockerfile is:

CMD ["dotnet", "Clients.Api.dll"]

**Comment by NCarlsonMSFT** [comment]
Sorry I'm still not sure I'm fully understanding the scenario, but:
When you hit stop the dotnet process is stopped, but the container is left running to be reused. If you want the process to run w/o the debugger you can use Ctrl+F5 to start the process w/o attaching to it (this can share the container used by debugging for optimal performance)
Note: With Ctrl+F5 in a container you'll still see the stop button, but VS is not in debug mode, that is a convenience feature to let you stop the process in the container.
Note2: The dotnet process in the container is automatically killed on build so that the build output is not locked
Note3: Hot Reload is supported with Ctrl+F5 so you can make changes and click the fire icon to push the change to the running process, no need to build or launch.

**Comment by DanPatten** [comment]
I want to debug the container and then when I hit stop I want the dotnet process to keep running. I can do this by manually starting the dotnet process again. I can't use hot reload yet since I'm still on .net 6 :(

**Comment by NCarlsonMSFT** [comment]
@DanPatten apologies apparently my response last week didn't post.
We don't plan to add support for automatically re-running the service after stopping.
The good news I have for you is that the tools is support Hot Reload for Ctrl+F5 with .NET 6 (For debugging you need .NET 8), so you can keep your service running while iterating on changes if you're not debugging.

**Comment by kamranayub** [comment]
> We don't plan to add support for automatically re-running the service after stopping.

I just want to chime in and say the DX due to this is not ideal.

I always forget to re-run Ctrl-F5 after building my distributed project. So the web app will be running fine in .NET Framework, which I don't think has this issue, but my .NET 10 app API server will constantly keep stopping because I'm building the solution or a project. Then everything breaks because the API won't respond, until I remember to Run without Debugging again.

I'm hoping to just switch totally off this and onto Aspire soon, but I did want to share why this is so frustrating.
