### ISSUE TITLE
Customize build command for docker project.

### ISSUE THREAD

**Issue by aensidhe** [Microsoft/DockerTools#51]
Our project is quite complex and we can't use `docker-compose build` in any case due to bug in `docker-compose`: https://github.com/docker/compose/issues/3886

We have our own build script for docker-compose and I would like to use it instead of usual `docker-compose up --build` to start project.

Can I achieve that?

**Comment by haniamr** [comment]
I don't believe there's a straight-forward/safe way that you can achieve that. One way is to create your own executable named "docker-compose.exe", have it in the PATH env variable instead of the default one "C:\Program Files\Docker\Docker\Resources\bin\docker-compose.exe".

So given your exe works exactly as docker-compose.exe (same parameters and does the same thing), this *might* work.

**Comment by aensidhe** [comment]
I would like to have some hooks like in usual MSBuild C# projects. BeforeBuild/AfterBuild/Build, etc.

**Comment by haniamr** [comment]
That is MSBuild already so you can override any of the targets defined here: 
%VSINSTALLDIR%\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets

The only thing to note is that target names are not guaranteed to be the same in future releases.
