### ISSUE TITLE
No Docker support for mstest projects

### ISSUE THREAD

**Issue by evil-shrike** [Microsoft/DockerTools#77]
There's NO Add -> "Docker support" command for MSTest projects.

If I add a Dockerfile into a mstest project and a service for it into my docker-compose DockerTools fails on build dcproj-project:
Object reference not set to an instance of an object.	docker-compose	
Source: Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	297

Running docker-compose from command line works just fine.

It's just showstopper issue as I can't debug my tests inside Docker.

Unfortunately it's absolutely unclear how to reproduce by hand all that logic that DockerTools do to run debugging :( Please see my [question](https://stackoverflow.com/questions/48661857/how-to-debug-a-net-core-app-runnig-in-linux-docker-container-from-visual-studio) on SO.

**Comment by JohnGalt1717** [comment]
Really there's no support for running tests in the docker environment at all.

And VS.net 2017 15.8 completely changes how docker works (no more compose files)

This needs to work so that tests can be run (optionally in VS.net) in the docker instance, with debugging and reporting of results.

And it needs to be easily enablable on vsts to run the unit tests, then if successful, build, and publish and then deploy to Azure.

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please let us know, we are happy to take a look!

**Comment by jzabroski** [comment]
It doesn't look like anyone at Microsoft even triaged or replied to this issue.
